//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Test.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/GoodFolks")]
    public partial class Member : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string UserAdressField;
        
        private System.DateTime UserBirthDateField;
        
        private string UserEducationField;
        
        private string UserEmailField;
        
        private string UserFNameField;
        
        private string UserGenderField;
        
        private int UserIdField;
        
        private string UserLNameField;
        
        private string UserNameField;
        
        private System.DateTime UserTimeCreatedField;
        
        private string UserTypeField;
        
        private string UserpasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAdress {
            get {
                return this.UserAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAdressField, value) != true)) {
                    this.UserAdressField = value;
                    this.RaisePropertyChanged("UserAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserBirthDate {
            get {
                return this.UserBirthDateField;
            }
            set {
                if ((this.UserBirthDateField.Equals(value) != true)) {
                    this.UserBirthDateField = value;
                    this.RaisePropertyChanged("UserBirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEducation {
            get {
                return this.UserEducationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEducationField, value) != true)) {
                    this.UserEducationField = value;
                    this.RaisePropertyChanged("UserEducation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFName {
            get {
                return this.UserFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFNameField, value) != true)) {
                    this.UserFNameField = value;
                    this.RaisePropertyChanged("UserFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGender {
            get {
                return this.UserGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGenderField, value) != true)) {
                    this.UserGenderField = value;
                    this.RaisePropertyChanged("UserGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLName {
            get {
                return this.UserLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLNameField, value) != true)) {
                    this.UserLNameField = value;
                    this.RaisePropertyChanged("UserLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserTimeCreated {
            get {
                return this.UserTimeCreatedField;
            }
            set {
                if ((this.UserTimeCreatedField.Equals(value) != true)) {
                    this.UserTimeCreatedField = value;
                    this.RaisePropertyChanged("UserTimeCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userpassword {
            get {
                return this.UserpasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserpasswordField, value) != true)) {
                    this.UserpasswordField = value;
                    this.RaisePropertyChanged("Userpassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAuth", Namespace="http://schemas.datacontract.org/2004/07/GoodFolks")]
    public partial class UserAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PasswordField;
        
        private int UserIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/GoodFolks")]
    public partial class Post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int postIdField;
        
        private byte[] postImageField;
        
        private string postLocationField;
        
        private string postTimeField;
        
        private char postTypeField;
        
        private int postUserField;
        
        private string txtContentField;
        
        private byte[] userImageField;
        
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int postId {
            get {
                return this.postIdField;
            }
            set {
                if ((this.postIdField.Equals(value) != true)) {
                    this.postIdField = value;
                    this.RaisePropertyChanged("postId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] postImage {
            get {
                return this.postImageField;
            }
            set {
                if ((object.ReferenceEquals(this.postImageField, value) != true)) {
                    this.postImageField = value;
                    this.RaisePropertyChanged("postImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postLocation {
            get {
                return this.postLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.postLocationField, value) != true)) {
                    this.postLocationField = value;
                    this.RaisePropertyChanged("postLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postTime {
            get {
                return this.postTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.postTimeField, value) != true)) {
                    this.postTimeField = value;
                    this.RaisePropertyChanged("postTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char postType {
            get {
                return this.postTypeField;
            }
            set {
                if ((this.postTypeField.Equals(value) != true)) {
                    this.postTypeField = value;
                    this.RaisePropertyChanged("postType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int postUser {
            get {
                return this.postUserField;
            }
            set {
                if ((this.postUserField.Equals(value) != true)) {
                    this.postUserField = value;
                    this.RaisePropertyChanged("postUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txtContent {
            get {
                return this.txtContentField;
            }
            set {
                if ((object.ReferenceEquals(this.txtContentField, value) != true)) {
                    this.txtContentField = value;
                    this.RaisePropertyChanged("txtContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] userImage {
            get {
                return this.userImageField;
            }
            set {
                if ((object.ReferenceEquals(this.userImageField, value) != true)) {
                    this.userImageField = value;
                    this.RaisePropertyChanged("userImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/GoodFolks")]
    public partial class Event : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int currentAttendingField;
        
        private string eventCaptionField;
        
        private string eventDateField;
        
        private int eventHostField;
        
        private int eventIdField;
        
        private string eventLocationField;
        
        private string eventNameField;
        
        private int eventTypeField;
        
        private int maxAttendField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentAttending {
            get {
                return this.currentAttendingField;
            }
            set {
                if ((this.currentAttendingField.Equals(value) != true)) {
                    this.currentAttendingField = value;
                    this.RaisePropertyChanged("currentAttending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventCaption {
            get {
                return this.eventCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.eventCaptionField, value) != true)) {
                    this.eventCaptionField = value;
                    this.RaisePropertyChanged("eventCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventDate {
            get {
                return this.eventDateField;
            }
            set {
                if ((object.ReferenceEquals(this.eventDateField, value) != true)) {
                    this.eventDateField = value;
                    this.RaisePropertyChanged("eventDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventHost {
            get {
                return this.eventHostField;
            }
            set {
                if ((this.eventHostField.Equals(value) != true)) {
                    this.eventHostField = value;
                    this.RaisePropertyChanged("eventHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventId {
            get {
                return this.eventIdField;
            }
            set {
                if ((this.eventIdField.Equals(value) != true)) {
                    this.eventIdField = value;
                    this.RaisePropertyChanged("eventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventLocation {
            get {
                return this.eventLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.eventLocationField, value) != true)) {
                    this.eventLocationField = value;
                    this.RaisePropertyChanged("eventLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventName {
            get {
                return this.eventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.eventNameField, value) != true)) {
                    this.eventNameField = value;
                    this.RaisePropertyChanged("eventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventType {
            get {
                return this.eventTypeField;
            }
            set {
                if ((this.eventTypeField.Equals(value) != true)) {
                    this.eventTypeField = value;
                    this.RaisePropertyChanged("eventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxAttend {
            get {
                return this.maxAttendField;
            }
            set {
                if ((this.maxAttendField.Equals(value) != true)) {
                    this.maxAttendField = value;
                    this.RaisePropertyChanged("maxAttend");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/newUser", ReplyAction="http://tempuri.org/IService1/newUserResponse")]
        System.IAsyncResult BeginnewUser(Test.ServiceReference1.Member newUser, System.AsyncCallback callback, object asyncState);
        
        bool EndnewUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Authenticate", ReplyAction="http://tempuri.org/IService1/AuthenticateResponse")]
        System.IAsyncResult BeginAuthenticate(Test.ServiceReference1.UserAuth user, System.AsyncCallback callback, object asyncState);
        
        int EndAuthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ForgotPassword", ReplyAction="http://tempuri.org/IService1/ForgotPasswordResponse")]
        System.IAsyncResult BeginForgotPassword(string emailOrUser, System.AsyncCallback callback, object asyncState);
        
        bool EndForgotPassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getFriendList", ReplyAction="http://tempuri.org/IService1/getFriendListResponse")]
        System.IAsyncResult BegingetFriendList(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> EndgetFriendList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getMemberInfo", ReplyAction="http://tempuri.org/IService1/getMemberInfoResponse")]
        System.IAsyncResult BegingetMemberInfo(int userId, System.AsyncCallback callback, object asyncState);
        
        Test.ServiceReference1.Member EndgetMemberInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getSalutes", ReplyAction="http://tempuri.org/IService1/getSalutesResponse")]
        System.IAsyncResult BegingetSalutes(int userId, System.AsyncCallback callback, object asyncState);
        
        int EndgetSalutes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getMyPosts", ReplyAction="http://tempuri.org/IService1/getMyPostsResponse")]
        System.IAsyncResult BegingetMyPosts(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetMyPosts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getFriendsPosts", ReplyAction="http://tempuri.org/IService1/getFriendsPostsResponse")]
        System.IAsyncResult BegingetFriendsPosts(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetFriendsPosts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getEvents", ReplyAction="http://tempuri.org/IService1/getEventsResponse")]
        System.IAsyncResult BegingetEvents(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> EndgetEvents(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getStrangerPosts", ReplyAction="http://tempuri.org/IService1/getStrangerPostsResponse")]
        System.IAsyncResult BegingetStrangerPosts(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetStrangerPosts(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Test.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class newUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public newUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForgotPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ForgotPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFriendListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFriendListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMemberInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMemberInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Test.ServiceReference1.Member Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Test.ServiceReference1.Member)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSalutesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSalutesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMyPostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMyPostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFriendsPostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFriendsPostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getStrangerPostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getStrangerPostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Test.ServiceReference1.IService1>, Test.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginnewUserDelegate;
        
        private EndOperationDelegate onEndnewUserDelegate;
        
        private System.Threading.SendOrPostCallback onnewUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginForgotPasswordDelegate;
        
        private EndOperationDelegate onEndForgotPasswordDelegate;
        
        private System.Threading.SendOrPostCallback onForgotPasswordCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFriendListDelegate;
        
        private EndOperationDelegate onEndgetFriendListDelegate;
        
        private System.Threading.SendOrPostCallback ongetFriendListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMemberInfoDelegate;
        
        private EndOperationDelegate onEndgetMemberInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetMemberInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSalutesDelegate;
        
        private EndOperationDelegate onEndgetSalutesDelegate;
        
        private System.Threading.SendOrPostCallback ongetSalutesCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMyPostsDelegate;
        
        private EndOperationDelegate onEndgetMyPostsDelegate;
        
        private System.Threading.SendOrPostCallback ongetMyPostsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFriendsPostsDelegate;
        
        private EndOperationDelegate onEndgetFriendsPostsDelegate;
        
        private System.Threading.SendOrPostCallback ongetFriendsPostsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetEventsDelegate;
        
        private EndOperationDelegate onEndgetEventsDelegate;
        
        private System.Threading.SendOrPostCallback ongetEventsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetStrangerPostsDelegate;
        
        private EndOperationDelegate onEndgetStrangerPostsDelegate;
        
        private System.Threading.SendOrPostCallback ongetStrangerPostsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<newUserCompletedEventArgs> newUserCompleted;
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<ForgotPasswordCompletedEventArgs> ForgotPasswordCompleted;
        
        public event System.EventHandler<getFriendListCompletedEventArgs> getFriendListCompleted;
        
        public event System.EventHandler<getMemberInfoCompletedEventArgs> getMemberInfoCompleted;
        
        public event System.EventHandler<getSalutesCompletedEventArgs> getSalutesCompleted;
        
        public event System.EventHandler<getMyPostsCompletedEventArgs> getMyPostsCompleted;
        
        public event System.EventHandler<getFriendsPostsCompletedEventArgs> getFriendsPostsCompleted;
        
        public event System.EventHandler<getEventsCompletedEventArgs> getEventsCompleted;
        
        public event System.EventHandler<getStrangerPostsCompletedEventArgs> getStrangerPostsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BeginnewUser(Test.ServiceReference1.Member newUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginnewUser(newUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool Test.ServiceReference1.IService1.EndnewUser(System.IAsyncResult result) {
            return base.Channel.EndnewUser(result);
        }
        
        private System.IAsyncResult OnBeginnewUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Test.ServiceReference1.Member newUser = ((Test.ServiceReference1.Member)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BeginnewUser(newUser, callback, asyncState);
        }
        
        private object[] OnEndnewUser(System.IAsyncResult result) {
            bool retVal = ((Test.ServiceReference1.IService1)(this)).EndnewUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnnewUserCompleted(object state) {
            if ((this.newUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.newUserCompleted(this, new newUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void newUserAsync(Test.ServiceReference1.Member newUser) {
            this.newUserAsync(newUser, null);
        }
        
        public void newUserAsync(Test.ServiceReference1.Member newUser, object userState) {
            if ((this.onBeginnewUserDelegate == null)) {
                this.onBeginnewUserDelegate = new BeginOperationDelegate(this.OnBeginnewUser);
            }
            if ((this.onEndnewUserDelegate == null)) {
                this.onEndnewUserDelegate = new EndOperationDelegate(this.OnEndnewUser);
            }
            if ((this.onnewUserCompletedDelegate == null)) {
                this.onnewUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnnewUserCompleted);
            }
            base.InvokeAsync(this.onBeginnewUserDelegate, new object[] {
                        newUser}, this.onEndnewUserDelegate, this.onnewUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BeginAuthenticate(Test.ServiceReference1.UserAuth user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Test.ServiceReference1.IService1.EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Test.ServiceReference1.UserAuth user = ((Test.ServiceReference1.UserAuth)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BeginAuthenticate(user, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            int retVal = ((Test.ServiceReference1.IService1)(this)).EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(Test.ServiceReference1.UserAuth user) {
            this.AuthenticateAsync(user, null);
        }
        
        public void AuthenticateAsync(Test.ServiceReference1.UserAuth user, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        user}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BeginForgotPassword(string emailOrUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginForgotPassword(emailOrUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool Test.ServiceReference1.IService1.EndForgotPassword(System.IAsyncResult result) {
            return base.Channel.EndForgotPassword(result);
        }
        
        private System.IAsyncResult OnBeginForgotPassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string emailOrUser = ((string)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BeginForgotPassword(emailOrUser, callback, asyncState);
        }
        
        private object[] OnEndForgotPassword(System.IAsyncResult result) {
            bool retVal = ((Test.ServiceReference1.IService1)(this)).EndForgotPassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnForgotPasswordCompleted(object state) {
            if ((this.ForgotPasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ForgotPasswordCompleted(this, new ForgotPasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ForgotPasswordAsync(string emailOrUser) {
            this.ForgotPasswordAsync(emailOrUser, null);
        }
        
        public void ForgotPasswordAsync(string emailOrUser, object userState) {
            if ((this.onBeginForgotPasswordDelegate == null)) {
                this.onBeginForgotPasswordDelegate = new BeginOperationDelegate(this.OnBeginForgotPassword);
            }
            if ((this.onEndForgotPasswordDelegate == null)) {
                this.onEndForgotPasswordDelegate = new EndOperationDelegate(this.OnEndForgotPassword);
            }
            if ((this.onForgotPasswordCompletedDelegate == null)) {
                this.onForgotPasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnForgotPasswordCompleted);
            }
            base.InvokeAsync(this.onBeginForgotPasswordDelegate, new object[] {
                        emailOrUser}, this.onEndForgotPasswordDelegate, this.onForgotPasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetFriendList(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFriendList(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> Test.ServiceReference1.IService1.EndgetFriendList(System.IAsyncResult result) {
            return base.Channel.EndgetFriendList(result);
        }
        
        private System.IAsyncResult OnBegingetFriendList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BegingetFriendList(userId, callback, asyncState);
        }
        
        private object[] OnEndgetFriendList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> retVal = ((Test.ServiceReference1.IService1)(this)).EndgetFriendList(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFriendListCompleted(object state) {
            if ((this.getFriendListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFriendListCompleted(this, new getFriendListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFriendListAsync(int userId) {
            this.getFriendListAsync(userId, null);
        }
        
        public void getFriendListAsync(int userId, object userState) {
            if ((this.onBegingetFriendListDelegate == null)) {
                this.onBegingetFriendListDelegate = new BeginOperationDelegate(this.OnBegingetFriendList);
            }
            if ((this.onEndgetFriendListDelegate == null)) {
                this.onEndgetFriendListDelegate = new EndOperationDelegate(this.OnEndgetFriendList);
            }
            if ((this.ongetFriendListCompletedDelegate == null)) {
                this.ongetFriendListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFriendListCompleted);
            }
            base.InvokeAsync(this.onBegingetFriendListDelegate, new object[] {
                        userId}, this.onEndgetFriendListDelegate, this.ongetFriendListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetMemberInfo(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMemberInfo(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference1.Member Test.ServiceReference1.IService1.EndgetMemberInfo(System.IAsyncResult result) {
            return base.Channel.EndgetMemberInfo(result);
        }
        
        private System.IAsyncResult OnBegingetMemberInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BegingetMemberInfo(userId, callback, asyncState);
        }
        
        private object[] OnEndgetMemberInfo(System.IAsyncResult result) {
            Test.ServiceReference1.Member retVal = ((Test.ServiceReference1.IService1)(this)).EndgetMemberInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMemberInfoCompleted(object state) {
            if ((this.getMemberInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMemberInfoCompleted(this, new getMemberInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMemberInfoAsync(int userId) {
            this.getMemberInfoAsync(userId, null);
        }
        
        public void getMemberInfoAsync(int userId, object userState) {
            if ((this.onBegingetMemberInfoDelegate == null)) {
                this.onBegingetMemberInfoDelegate = new BeginOperationDelegate(this.OnBegingetMemberInfo);
            }
            if ((this.onEndgetMemberInfoDelegate == null)) {
                this.onEndgetMemberInfoDelegate = new EndOperationDelegate(this.OnEndgetMemberInfo);
            }
            if ((this.ongetMemberInfoCompletedDelegate == null)) {
                this.ongetMemberInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMemberInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetMemberInfoDelegate, new object[] {
                        userId}, this.onEndgetMemberInfoDelegate, this.ongetMemberInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetSalutes(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSalutes(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Test.ServiceReference1.IService1.EndgetSalutes(System.IAsyncResult result) {
            return base.Channel.EndgetSalutes(result);
        }
        
        private System.IAsyncResult OnBegingetSalutes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BegingetSalutes(userId, callback, asyncState);
        }
        
        private object[] OnEndgetSalutes(System.IAsyncResult result) {
            int retVal = ((Test.ServiceReference1.IService1)(this)).EndgetSalutes(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSalutesCompleted(object state) {
            if ((this.getSalutesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSalutesCompleted(this, new getSalutesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSalutesAsync(int userId) {
            this.getSalutesAsync(userId, null);
        }
        
        public void getSalutesAsync(int userId, object userState) {
            if ((this.onBegingetSalutesDelegate == null)) {
                this.onBegingetSalutesDelegate = new BeginOperationDelegate(this.OnBegingetSalutes);
            }
            if ((this.onEndgetSalutesDelegate == null)) {
                this.onEndgetSalutesDelegate = new EndOperationDelegate(this.OnEndgetSalutes);
            }
            if ((this.ongetSalutesCompletedDelegate == null)) {
                this.ongetSalutesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSalutesCompleted);
            }
            base.InvokeAsync(this.onBegingetSalutesDelegate, new object[] {
                        userId}, this.onEndgetSalutesDelegate, this.ongetSalutesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetMyPosts(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMyPosts(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Test.ServiceReference1.IService1.EndgetMyPosts(System.IAsyncResult result) {
            return base.Channel.EndgetMyPosts(result);
        }
        
        private System.IAsyncResult OnBegingetMyPosts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BegingetMyPosts(userId, callback, asyncState);
        }
        
        private object[] OnEndgetMyPosts(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> retVal = ((Test.ServiceReference1.IService1)(this)).EndgetMyPosts(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMyPostsCompleted(object state) {
            if ((this.getMyPostsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMyPostsCompleted(this, new getMyPostsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMyPostsAsync(int userId) {
            this.getMyPostsAsync(userId, null);
        }
        
        public void getMyPostsAsync(int userId, object userState) {
            if ((this.onBegingetMyPostsDelegate == null)) {
                this.onBegingetMyPostsDelegate = new BeginOperationDelegate(this.OnBegingetMyPosts);
            }
            if ((this.onEndgetMyPostsDelegate == null)) {
                this.onEndgetMyPostsDelegate = new EndOperationDelegate(this.OnEndgetMyPosts);
            }
            if ((this.ongetMyPostsCompletedDelegate == null)) {
                this.ongetMyPostsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMyPostsCompleted);
            }
            base.InvokeAsync(this.onBegingetMyPostsDelegate, new object[] {
                        userId}, this.onEndgetMyPostsDelegate, this.ongetMyPostsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetFriendsPosts(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFriendsPosts(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Test.ServiceReference1.IService1.EndgetFriendsPosts(System.IAsyncResult result) {
            return base.Channel.EndgetFriendsPosts(result);
        }
        
        private System.IAsyncResult OnBegingetFriendsPosts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((Test.ServiceReference1.IService1)(this)).BegingetFriendsPosts(userId, callback, asyncState);
        }
        
        private object[] OnEndgetFriendsPosts(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> retVal = ((Test.ServiceReference1.IService1)(this)).EndgetFriendsPosts(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFriendsPostsCompleted(object state) {
            if ((this.getFriendsPostsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFriendsPostsCompleted(this, new getFriendsPostsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFriendsPostsAsync(int userId) {
            this.getFriendsPostsAsync(userId, null);
        }
        
        public void getFriendsPostsAsync(int userId, object userState) {
            if ((this.onBegingetFriendsPostsDelegate == null)) {
                this.onBegingetFriendsPostsDelegate = new BeginOperationDelegate(this.OnBegingetFriendsPosts);
            }
            if ((this.onEndgetFriendsPostsDelegate == null)) {
                this.onEndgetFriendsPostsDelegate = new EndOperationDelegate(this.OnEndgetFriendsPosts);
            }
            if ((this.ongetFriendsPostsCompletedDelegate == null)) {
                this.ongetFriendsPostsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFriendsPostsCompleted);
            }
            base.InvokeAsync(this.onBegingetFriendsPostsDelegate, new object[] {
                        userId}, this.onEndgetFriendsPostsDelegate, this.ongetFriendsPostsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetEvents(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetEvents(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> Test.ServiceReference1.IService1.EndgetEvents(System.IAsyncResult result) {
            return base.Channel.EndgetEvents(result);
        }
        
        private System.IAsyncResult OnBegingetEvents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Test.ServiceReference1.IService1)(this)).BegingetEvents(callback, asyncState);
        }
        
        private object[] OnEndgetEvents(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> retVal = ((Test.ServiceReference1.IService1)(this)).EndgetEvents(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetEventsCompleted(object state) {
            if ((this.getEventsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getEventsCompleted(this, new getEventsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getEventsAsync() {
            this.getEventsAsync(null);
        }
        
        public void getEventsAsync(object userState) {
            if ((this.onBegingetEventsDelegate == null)) {
                this.onBegingetEventsDelegate = new BeginOperationDelegate(this.OnBegingetEvents);
            }
            if ((this.onEndgetEventsDelegate == null)) {
                this.onEndgetEventsDelegate = new EndOperationDelegate(this.OnEndgetEvents);
            }
            if ((this.ongetEventsCompletedDelegate == null)) {
                this.ongetEventsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetEventsCompleted);
            }
            base.InvokeAsync(this.onBegingetEventsDelegate, null, this.onEndgetEventsDelegate, this.ongetEventsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Test.ServiceReference1.IService1.BegingetStrangerPosts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetStrangerPosts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> Test.ServiceReference1.IService1.EndgetStrangerPosts(System.IAsyncResult result) {
            return base.Channel.EndgetStrangerPosts(result);
        }
        
        private System.IAsyncResult OnBegingetStrangerPosts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Test.ServiceReference1.IService1)(this)).BegingetStrangerPosts(callback, asyncState);
        }
        
        private object[] OnEndgetStrangerPosts(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> retVal = ((Test.ServiceReference1.IService1)(this)).EndgetStrangerPosts(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetStrangerPostsCompleted(object state) {
            if ((this.getStrangerPostsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getStrangerPostsCompleted(this, new getStrangerPostsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getStrangerPostsAsync() {
            this.getStrangerPostsAsync(null);
        }
        
        public void getStrangerPostsAsync(object userState) {
            if ((this.onBegingetStrangerPostsDelegate == null)) {
                this.onBegingetStrangerPostsDelegate = new BeginOperationDelegate(this.OnBegingetStrangerPosts);
            }
            if ((this.onEndgetStrangerPostsDelegate == null)) {
                this.onEndgetStrangerPostsDelegate = new EndOperationDelegate(this.OnEndgetStrangerPosts);
            }
            if ((this.ongetStrangerPostsCompletedDelegate == null)) {
                this.ongetStrangerPostsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetStrangerPostsCompleted);
            }
            base.InvokeAsync(this.onBegingetStrangerPostsDelegate, null, this.onEndgetStrangerPostsDelegate, this.ongetStrangerPostsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Test.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Test.ServiceReference1.IService1>, Test.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Test.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginnewUser(Test.ServiceReference1.Member newUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = newUser;
                System.IAsyncResult _result = base.BeginInvoke("newUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndnewUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("newUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticate(Test.ServiceReference1.UserAuth user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("Authenticate", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAuthenticate(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Authenticate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginForgotPassword(string emailOrUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = emailOrUser;
                System.IAsyncResult _result = base.BeginInvoke("ForgotPassword", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndForgotPassword(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ForgotPassword", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetFriendList(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("getFriendList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> EndgetFriendList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member> _result = ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Member>)(base.EndInvoke("getFriendList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetMemberInfo(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("getMemberInfo", _args, callback, asyncState);
                return _result;
            }
            
            public Test.ServiceReference1.Member EndgetMemberInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                Test.ServiceReference1.Member _result = ((Test.ServiceReference1.Member)(base.EndInvoke("getMemberInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSalutes(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("getSalutes", _args, callback, asyncState);
                return _result;
            }
            
            public int EndgetSalutes(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("getSalutes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetMyPosts(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("getMyPosts", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetMyPosts(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> _result = ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(base.EndInvoke("getMyPosts", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetFriendsPosts(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("getFriendsPosts", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetFriendsPosts(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> _result = ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(base.EndInvoke("getFriendsPosts", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetEvents(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getEvents", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> EndgetEvents(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event> _result = ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Event>)(base.EndInvoke("getEvents", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetStrangerPosts(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getStrangerPosts", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> EndgetStrangerPosts(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post> _result = ((System.Collections.ObjectModel.ObservableCollection<Test.ServiceReference1.Post>)(base.EndInvoke("getStrangerPosts", _args, result)));
                return _result;
            }
        }
    }
}
