//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_government_Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M_government_Application.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of service do you want to apply for ?.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions :.
        /// </summary>
        public static string Cond {
            get {
                return ResourceManager.GetString("Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t go to the next step until you answer the conditions questions .
        /// </summary>
        public static string Condnext {
            get {
                return ResourceManager.GetString("Condnext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should fulfill this condition to apply for this service.
        /// </summary>
        public static string Condno {
            get {
                return ResourceManager.GetString("Condno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have fulfilled all the conditions , CLICK next to complete..
        /// </summary>
        public static string Condq {
            get {
                return ResourceManager.GetString("Condq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Definition :.
        /// </summary>
        public static string Def {
            get {
                return ResourceManager.GetString("Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Documents :.
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a missing document, double check the requirements.
        /// </summary>
        public static string Docdone {
            get {
                return ResourceManager.GetString("Docdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        public static string Employeer {
            get {
                return ResourceManager.GetString("Employeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees :.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page .
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to apply : .
        /// </summary>
        public static string Loca {
            get {
                return ResourceManager.GetString("Loca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ServiceGroup :  .
        /// </summary>
        public static string Mainser {
            get {
                return ResourceManager.GetString("Mainser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conditions.
        /// </summary>
        public static string Nocon {
            get {
                return ResourceManager.GetString("Nocon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE .
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose either Sub-Service or Service.
        /// </summary>
        public static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to process the service :.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SELECT Sub-Service or Service first.
        /// </summary>
        public static string Selectser {
            get {
                return ResourceManager.GetString("Selectser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string Ser {
            get {
                return ResourceManager.GetString("Ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        public static string SerType {
            get {
                return ResourceManager.GetString("SerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dabtyh.
        /// </summary>
        public static string SerType2 {
            get {
                return ResourceManager.GetString("SerType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name :.
        /// </summary>
        public static string Servicename {
            get {
                return ResourceManager.GetString("Servicename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to follow :.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub- Service:.
        /// </summary>
        public static string Subser {
            get {
                return ResourceManager.GetString("Subser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceType :.
        /// </summary>
        public static string Typeser {
            get {
                return ResourceManager.GetString("Typeser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
